- name: Installing Postfix
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'postfix'

- name: Set mailname
  copy:
    content: "{{ postfix_mydomain }}"
    dest: /etc/mailname

- name: Configure Postfix
  template:
    src: main.j2
    dest: /etc/postfix/main.cf

- name: Restart postfix
  service:
    name: postfix
    state: restarted
    enabled: yes
