---
- name: Stopping Jenkins
  service:
    name: jenkins
    state: stopped

- name: Configuring Jenkins
  file:
    path: "{{ jenkins_install_dir }}/users/admin"
    state: directory

- name: "Adding User: Scoring"
  copy:
    src: "../files/users/scoring"
    dest: "{{ jenkins_install_dir }}/users"

- name: "Configuring port"
  replace:
    path: /usr/local/etc/rc.d/jenkins
    regexp: '(--httpPort)=\d+'
    replace: '\1=8080'
  
- name: "Configuring web url"
  replace:
    path: /usr/local/etc/rc.d/jenkins
    regexp: '(--prefix=).*"'
    replace: '\1"'

- name: "Setting permissions"
  file:
    path: "{{ jenkins_install_dir }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    recurse: yes

- name: Bypassing Install
  lineinfile:
    path: "{{ jenkins_install_dir }}/jenkins.install.InstallUtil.lastExecVersion"
    line: "2.89.2"
    create: yes
    state: present

- name: Starting Jenkins
  service:
    name: jenkins
    state: started

