- name: Installing Jenkins
  pkgng:
    name: '{{ item }}'
    state: present
  with_items:
    - 'jenkins-lts'

- name: Starting Jenkins
  service:
    name: jenkins
    state: started

- name: "Waiting for service..."
  pause:
    seconds: 3
