- name: Installing Dovecot
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'dovecot-core'
    - 'dovecot-imapd'

- name: Configure Dovecot
  copy:
    src: ../files/dovecot.conf
    dest: /etc/dovecot/dovecot.conf

- name: Restart Dovecot
  service:
    name: dovecot
    state: restarted
    enabled: yes
